# Generated by Django 6.0.2 on 2026-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('rpg', 'RPG'), ('strategy', 'Strategy'), ('adventure', 'Adventure'), ('survival', 'Survival'), ('sandbox', 'Sandbox'), ('shooter', 'Shooter'), ('simulation', 'Simulation'), ('horror', 'Horror'), ('sport', 'Sport'), ('racing', 'Racing'), ('indie', 'Indie')], max_length=50),
        ),
    ]
